<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Faker\Factory as Faker;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Carbon\Carbon;

use Datetime;
use DatePeriod;
use DateInterval;


class AcademicMembership extends Seeder
{
    public $newDate;
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        $newDate=date('d-m-Y', strtotime("+2 months"));
        $faker = Faker::create('App\Models\AcademicMembership');
        $status = 1;

        $data = [
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
            [
                'position_title_id' => '1',
                'organization_id' => '1',
                'term_start' => date('Y-m-d'),
                'term_end' => $newDate,
                'first_name' => $faker->firstName($gender = null|'male'|'female'),
                'middle_name' => $faker->firstName($gender = null|'male'|'female'),
                'last_name' => $faker->lastname(),
                'suffix' => $faker->suffix(),
                'signature' => '...',
                'status' => $status,
                'created_at' => date('Y-m-d H:i:s'),
                'updated_at' => date('Y-m-d H:i:s'),
            ],
        ];

        DB::table('academic_members')->insert($data);
    }
}
